name: Flutter Windows CI/CD with Inno Setup

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows_installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      # ✅ Install yq properly on Windows
      - name: Install yq
        shell: pwsh
        run: choco install yq -y

      # ✅ Get app version from pubspec.yaml
      - name: Get app version
        id: get_version
        shell: pwsh
        run: |
          $version = (yq eval '.version' pubspec.yaml)
          echo "APP_VERSION=$version" >> $env:GITHUB_ENV

      # ✅ Build Windows release
      - name: Build Windows Release
        run: flutter build windows -t lib/main.dart --dart-define=FLAVOR=dev

      # ✅ Install Inno Setup
      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      # ✅ Create Windows installer with version
      - name: Create Windows installer
        shell: cmd
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss'
        env:
          BUILD_VERSION: ${{ env.APP_VERSION }}

      # ✅ Upload Installer Artifact
      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ABTEX_Windows_Installer_"${{ env.APP_VERSION }}"
          path: dist/*.exe
