name: Flutter Windows CI/CD with Inno Setup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_windows_installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes
          echo "✅ Inno Setup installed successfully"

      - name: Create Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: ab-tex-installer
          path: dist/ab_tex_setup.exe
