  name: Flutter Windows CI/CD with Inno Setup

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build_windows_installer:
      runs-on: windows-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Flutter
          uses: subosito/flutter-action@v2.16.0 # Pinned version
          with:
            flutter-version-file: '.flutter-version' # Use version file
            cache: true # Enable caching

        - name: Enable Windows Desktop
          run: flutter config --enable-windows-desktop

        - name: Install dependencies
          run: flutter pub get

        - name: Install yq
          shell: pwsh
          run: choco install yq -y

        - name: Get app version
          id: get_version
          shell: pwsh
          run: |
            $version = (yq eval '.version' pubspec.yaml)
            $safeVersion = $version -replace '\+', '_'
            echo "APP_VERSION=$safeVersion" >> $env:GITHUB_ENV

        - name: Build Windows Release
          run: flutter build windows -t lib/main.dart --dart-define=FLAVOR=dev

        - name: Install Inno Setup
          run: choco install innosetup --no-progress -y

        - name: Add Inno Setup to PATH
          run: echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        - name: Create Windows installer
          run: iscc installer.iss
          env:
            BUILD_VERSION: ${{ env.APP_VERSION }}

        - name: Upload Installer Artifact
          uses: actions/upload-artifact@v4
          with:
            name: ABTEX_Windows_Installer_${{ env.APP_VERSION }}
            path: dist/*.exe
            if-no-files-found: warn
